### ISSUE TITLE
`on_message` doesn't appear to be firing

### ISSUE THREAD

**Issue by estiens** [mispy/twitter_ebooks#100]
I don't seem to be receiving DMs through the bot (everything else works swimmingly). When the bot receives a DM, there is nothing the log nor is the on_message method firing.

**Comment by mispy** [comment]
yeah, this seems to be an upstream issue. not sure what's going on there https://github.com/sferik/twitter/issues/722

**Comment by estiens** [comment]
I just noticed that the twitter application now has 3 permission levels 'read', 'read/write', and 'read/write/access direct messages'. I'm going to regenerate my tokens using the DM permission level and see if that fixes it.

**Comment by estiens** [comment]
![image](https://cloud.githubusercontent.com/assets/4022668/12306166/08707cde-b9fe-11e5-80c7-0b54af6c87b8.png)

**Comment by estiens** [comment]
Fixed it by regenerating tokens...

**Comment by mispy** [comment]
oh. huh. that... fixed it for me too. well, there you go!
