### ISSUE TITLE
Import both plain text and Twitter for a single bot (Multiple data sources)

### ISSUE THREAD

**Issue by ZacharyDuBois** [mispy/twitter_ebooks#115]
It would be awesome if there was support for multiple data sources to feed some text into the system to speed up the learning.

Example:
You archive the user's tweets and grep and filter their IRC logs and then consume them both into one model for one bot.

**Comment by negatendo** [comment]
fwiw the consume command can be used to read in .json (with values for 'tweet'), .csv (with values for column named 'tweet'), and even lines from a text file (one line = one 'tweet'): https://github.com/mispy/twitter_ebooks/blob/master/lib/twitter_ebooks/model.rb#L142

**Comment by ZacharyDuBois** [comment]
@negatendo That was extremely helpful :+1: Thanks :)
