### ISSUE TITLE
Stopword = never tweet?

### ISSUE THREAD

**Issue by thewesker** [mispy/twitter_ebooks#123]
Is it possible to make a list of words the bot should never tweet? I know stopwords de-emphasizes words but is there a way, beyond editing archives manually, a way to create a list of banned words the bot should never tweet?

**Comment by Chenny2** [comment]
You have the power with bots.rb
I forgot where I got the code for this but something like that should work.
https://gist.github.com/Chenny2/c7091fabb0087a5c7463f6d48db64a88

**Comment by mispy** [comment]
This functionality is beyond the scope of the library itself, but not hard to implement yourself by having your bots.rb code check the output of a model before tweeting it, yep :)
