### ISSUE TITLE
Any way to consume multiple files to the same model?

### ISSUE THREAD

**Issue by jstray** [mispy/twitter_ebooks#135]
I'm trying to make bot based on both scraped tweets and other text files. But each run of `ebooks consume` writes to a new model file. Any way to merge into an existing model?

**Comment by nathancrank** [comment]
Not sure about from the command line, but in Ruby the `Ebooks::Model.consume_all` can do exactly this.

**Comment by smileytechguy** [comment]
there could be a way to concatenate the input files

**Comment by pazzjurist** [comment]
You can do ebooks consume-all from the CLI. Just typing "ebooks" alone will give you the different options you can use.
