### ISSUE TITLE
can't get 'ebooks archive' to authenticate

### ISSUE THREAD

**Issue by tape-** [mispy/twitter_ebooks#49]
I was having this problem with an older 2.x version as well. I thought it might have been a ruby 1.9 problem so I upgraded to ruby 2.0, but the problem still persists:

(21:42:56) tape@charles:~/twitter_ebooks/tape> ebooks archive tape
New archive for @tape at corpus/tape.json
/var/lib/gems/2.0.0/gems/twitter-5.13.0/lib/twitter/rest/response/raise_error.rb:15:in `on_complete': Could not authenticate you (Twitter::Error::Unauthorized)
    from /var/lib/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/response.rb:9:in`block in call'
    from /var/lib/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'
    from /var/lib/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/response.rb:8:in`call'
    from /var/lib/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/request/url_encoded.rb:15:in `call'
    from /var/lib/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/request/multipart.rb:14:in`call'
    from /var/lib/gems/2.0.0/gems/twitter-5.13.0/lib/twitter/rest/request/multipart_with_file.rb:17:in `call'
    from /var/lib/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in`build_response'
    from /var/lib/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
    from /var/lib/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/connection.rb:140:in`get'
    from /var/lib/gems/2.0.0/gems/twitter-5.13.0/lib/twitter/rest/request.rb:33:in `perform'
    from /var/lib/gems/2.0.0/gems/twitter-5.13.0/lib/twitter/rest/utils.rb:51:in`perform_request'
    from /var/lib/gems/2.0.0/gems/twitter-5.13.0/lib/twitter/rest/utils.rb:96:in `perform_request_with_objects'
    from /var/lib/gems/2.0.0/gems/twitter-5.13.0/lib/twitter/rest/utils.rb:140:in`objects_from_response_with_user'
    from /var/lib/gems/2.0.0/gems/twitter-5.13.0/lib/twitter/rest/timelines.rb:49:in `user_timeline'
    from /var/lib/gems/2.0.0/gems/twitter_ebooks-3.0.4/lib/twitter_ebooks/archive.rb:77:in`block in sync'
    from /var/lib/gems/2.0.0/gems/twitter_ebooks-3.0.4/lib/twitter_ebooks/archive.rb:74:in `loop'
    from /var/lib/gems/2.0.0/gems/twitter_ebooks-3.0.4/lib/twitter_ebooks/archive.rb:74:in`sync'
    from /var/lib/gems/2.0.0/gems/twitter_ebooks-3.0.4/bin/ebooks:152:in `archive'
    from /var/lib/gems/2.0.0/gems/twitter_ebooks-3.0.4/bin/ebooks:324:in`command'
    from /var/lib/gems/2.0.0/gems/twitter_ebooks-3.0.4/bin/ebooks:341:in `<top (required)>'
    from /usr/local/bin/ebooks:23:in`load'
    from /usr/local/bin/ebooks:23:in `<main>'

currently have twitter_ebooks 3.0.4.

**Comment by Zerhariel** [comment]
Hello,

I have the same issue but can't seem to find the ~\.ebooksrc file. Where could it be ?

**Comment by abhinavchh** [comment]
@Zerhariel it's in Users/YOURNAME/.ebooksrc

**Comment by AugustMiller** [comment]
In case you've found your way here after creating a new Twitter account and can't figure out why the keys from the app's page don't work—make sure your email is confirmed, then re-generate the token and secret. Then, as mentioned, drop them into `~/.ebooksrc` and your Heroku app's environment variables.
