### ISSUE TITLE
Utility to convert twitter archive .js files to twitter_ebooks compatible json

### ISSUE THREAD

**Issue by elad661** [mispy/twitter_ebooks#59]
It would be awesome if there was a built in utility to convert twitter's archive .js files to a json file that twitter_ebooks can parse.

**Comment by rockbandit** [comment]
twitter_ebooks should actually be able to read the csv file that's included with your Twitter archive. Copy the tweets.csv file into whatever folder you're working in (or just make sure you properly point to it) and then run: ebooks consume tweets.csv

Tada! No need to try and parse all the individual months that are found in the /data/js/tweets/ directory of your Twitter archive.

**Comment by brighid** [comment]
@rockbandit's solution worked for me. Also: the `README.txt` that comes with your Twitter archive suggests "To consume the export in a generic JSON parser in any language, strip the first and last lines of each file." So you can push each of the js files through `cat myfile | sed $d | perl -ne 'print if $. != 1' > newfile` and wind up with a usable JSON file.

**Comment by mispy** [comment]
As rockbandit notes, you can consume the csv from twitter archives directly. If you want to convert the csv file to json, "ebooks jsonify" in 3.0.9 will do that too :)
