### ISSUE TITLE
`on_startup` doesn't seem to happen ever...

### ISSUE THREAD

**Issue by davidcelis** [mispy/twitter_ebooks#71]
Hey; I'm on the latest version of twitter_ebooks. I have my bot running on Heroku, and it doesn't seem to be tweeting. My `on_startup` usually looks like this:

```ruby
def on_startup
  # 10% chance to make a tweet in any hour
  if rand > 0.9
    tweet(model.make_statement)
  end
end
```

My bot hasn't written its own tweet in almost two weeks. This started right about the time I upgraded to the latest major version of twitter_ebooks. To debug, I removed the conditional statement. So, after deploys, my bot should be immediately tweeting. But it isn't. A quick call of `heroku logs` also shows no errors. Only that my bot is streaming tweets. This makes me think there might be something up with the `on_startup` method... Any thoughts?

**Comment by davidcelis** [comment]
Oh! I should mention that if I do `heroku run irb`, load my bot, and call `bot.tweet(bot.model.make_statement)` manually, it'll post a tweet like usual.

**Comment by negatendo** [comment]
This would cause the bot to have a chance of tweeting *once* on startup. If you want the bot to tweet regularly you'll want a separate section in the behaviors to define that schedule. See the ebooks example: https://github.com/mispy/ebooks_example

**Comment by davidcelis** [comment]
Sorry that was a mistake in my example; I should have just copied and pasted:

```ruby
def on_startup
  # 10% chance to tweet something in any 60 minute interval
  scheduler.every '1h' do
    if rand > 0.90
      tweet(model.make_statement)
    end
  end
end
```

For my test I removed both the scheduler and `if` conditional, expecting it to make a tweet on startup, but it doesn't.

**Comment by davidcelis** [comment]
I found the issue. `on_startup` is fired by calling `prepare` on the bot, which I wasn't doing.
