### ISSUE TITLE
on_retweet event

### ISSUE THREAD

**Issue by jronallo** [mispy/twitter_ebooks#76]
Is there an event triggered in the streaming API for a retweet? Would it be possible or desireable to add a way to create an on_retweet handler? Maybe this is already possible? Currently I schedule a job to check for rewteets in the REST API. I would like to know about retweets sooner than I can with a scheduled job.

My use case is when someone retweets an image my bot created the bot then further manipulates that image as a way to thank them. (BTW, including #noRT in the retweet disables this feature in order to be nice for those who do not want a response.)

**Comment by negatendo** [comment]
If anyone is still wondering about this, the streaming API does not trigger a separate event for a retweeted. It's considered are a property of a tweet in the stream. See "retweeted" https://dev.twitter.com/overview/api/tweets
