### ISSUE TITLE
No unicode in keywords

### ISSUE THREAD

**Issue by ripperdoc** [mispy/twitter_ebooks#77]
When I use unicode input, all keywords get cutoff at that unicode. I found the reason.
In nlp.rb, line 102:
```
set :word_pattern, /(?<!@)(?<=\s)[\w']+/
```
should be
```
set :word_pattern, /(?<!@)(?<=\s)[\p{Word}']+/
```

**Comment by Gotos** [comment]
This still seams to be an issue. German Umlauts ä, ö, ü and ß still cause these problems.
