### ISSUE TITLE
infinite loop in very small models

### ISSUE THREAD

**Issue by jmhodges** [mispy/twitter_ebooks#78]
If a model has very few tokens (say, there's only two tweets and two words in each), Model#make_statement will fall into an infinite loop because the generated tiki array will always be smaller than 3.

[This line](https://github.com/mispy/twitter_ebooks/blob/bab8d77556be7f683b1356a5a4e935e5d748b1ca/lib/twitter_ebooks/model.rb#L221) causes it.

I was able to get this to happen with only two sentences being sent to consume_lines before calling make_statement: `'foobar baz"'` and `'foobar quux'`.

 Obviously, this is very edge-case-y.

**Comment by mispy** [comment]
This could also cause issues in models with lots of tweets but all of them very short
