### ISSUE TITLE
when variant is nil, multiple passes are performed to no avail

### ISSUE THREAD

**Issue by jmhodges** [mispy/twitter_ebooks#79]
When no suitable sentence is found and variant is nil in SuffixGenerator.generate, the upto loop is not exited, and no changes are done to find another sentence before looping again on the same tikis variable (which will always get the same result). This means that the same work is being done for every loop with no improvement.

What's supposed to happen there? I imagine a break. Something like replacing `tikis = variant if variant` with `if variant; tikis = variant; else; break; end` so that the caller of generate can try again.

**Comment by jmhodges** [comment]
I plugged the one option in, but another alternative is to use the remaining passes but with a different tikis if variant is nil. I'm not sure which would get better results. Just breaking would kick it out to the Model that might have enough retries to call it again but it might run out and have to go back to unigrams.

I imagine y'all have better thoughts on this than me.

**Comment by jmhodges** [comment]
This is complicated by the fact that the verbatim check is only done after exiting the Model's bigrams generation loop but is done inside the SuffixGenerator. So what could be a decent bigram result if a different starting sentence was chosen by the SuffixGenerator falls into a unigram result without the Model retrying the bigram generation.

**Comment by mispy** [comment]
Good catch. Generally from what I've seen it only hits the retry limit if it really can't make anything
