### ISSUE TITLE
shuffle and sample both used in SuffixGenerator.generate

### ISSUE THREAD

**Issue by jmhodges** [mispy/twitter_ebooks#80]
In SuffixGenerator.generate, there is this code:

    start = site[0]

    site[1].shuffle.each do |alt|
      start, alt = site[0], site[1].sample
      ...
    end

The shuffle and and the sample seem to be performing the same job and it could be turned into:

    start = site[0]

    site[1].shuffle.each do |alt|
      ...
    end

with no change (other than the obvious pulling from a random source one less time).

**Comment by mispy** [comment]
right you are. must've been left over from some refactoring
