### ISSUE TITLE
Bot runs but doesn't tweet

### ISSUE THREAD

**Issue by BelladonnaToxin** [mispy/twitter_ebooks#83]
While ebooks tweet <model_path> <botname> works just fine and I'm able to send as many tweets I like through this method, using ebooks start displays this.
 ![ebooks start](http://i.imgur.com/7CeD2Ad.png)
While running, the bot will report follows, mentions and the like but it never tweets or replies. Am I missing something or is there a fix?

**Comment by mispy** [comment]
what does your bot code look like?

**Comment by BelladonnaToxin** [comment]
bots.rb? It's the same as the version you supplied with my keys pasted in. The only difference would be the time, which I changed to

  def on_startup
    scheduler.every '10m' do
      # Tweet something every 10 minutes
      # See https://github.com/jmettraux/rufus-scheduler
      # tweet("hi")
      # pictweet("hi", "cuteselfie.jpg")
    end
  end

**Comment by mispy** [comment]
The bots.rb in the README is a very basic template-- it's not meant to do very much out of the box. A # at the beginning of a line in Ruby means it is commented out and won't run at all. If you want to run a full bot, try https://github.com/mispy/ebooks_example :)

**Comment by BelladonnaToxin** [comment]
Ah, sorry, hehe. I was following BooDoo's old tutorial and since I ran into quite a few problems, I tried re-doing everything with the newest version of Ruby and your bot and didn't realise this version would do less. Thank you ^^
