### ISSUE TITLE
tests failing because of uninitialized constant GC::INTERNAL_CONSTANTS

### ISSUE THREAD

**Issue by negatendo** [mispy/twitter_ebooks#84]
I'm having trouble getting the provided tests to run without failures. It seems the memory profiling bits might be missing something in my environment. Has anyone else experienced this issue?

Failures:

  1) Ebooks::Model consumes, saves and loads models correctly
     Failure/Error: report = MemoryUsage.report do
     NameError:
       uninitialized constant GC::INTERNAL_CONSTANTS
     # ./spec/memprof.rb:11:in `report'
     # ./spec/model_spec.rb:28:in `block (2 levels) in <top (required)>'

**Comment by mispy** [comment]
Are you using Ruby 2.1+? That's when it was introduced

**Comment by negatendo** [comment]
I may not have been! I'll try again with ruby 2.1+ thanks.

**Comment by negatendo** [comment]
Got tests working fine by the way. Apologies for the delay in follow-up.
