### ISSUE TITLE
ebooks start syntax error

### ISSUE THREAD

**Issue by grrful** [mispy/twitter_ebooks#90]
whenever i do run ebooks start, i get the following: 

<code>C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/twitter_ebooks-3.1.0/bin/ebooks:354:in `
load': bots.rb:137: syntax error, unexpected keyword_end, expecting end-of-input
 (SyntaxError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/twitter_ebooks-3.1.0/bin/eb
ooks:354:in `load_bots'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/twitter_ebooks-3.1.0/bin/eb
ooks:285:in `start'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/twitter_ebooks-3.1.0/bin/eb
ooks:378:in `command'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/twitter_ebooks-3.1.0/bin/eb
ooks:389:in `<top (required)>'
        from C:/Ruby200-x64/bin/ebooks:23:in `load'
        from C:/Ruby200-x64/bin/ebooks:23:in `/main/'

</code>

I'm guessing the syntax error is in the bots.rb file, but I'm not sure what it is since it's an exact copy of the ebooks_example bots.rb populated with the twitter keys, and username.

*main is in angle brackets

**Comment by mispy** [comment]
You have one too many ends, might've copy/pasted something oddly somewhere. I'd suggest working with a fresh clone
