### ISSUE TITLE
ebooks start failure: EADDRNOTAVAIL: Can't assign requested address - connect(2)

### ISSUE THREAD

**Issue by rachelhyman** [mispy/twitter_ebooks#91]
I kept getting this error when I tried to run `ebooks start`. I traced it to a TCP connection issue with version 5.15.0 of the twitter gem: https://github.com/sferik/twitter/issues/709

My workaround was to uninstall v. 5.15.0 of the twitter gem, and install 5.14.0, which fixes it. I understand this isn't an issue with your repo specifically, but wanted to make it easier for other people to find a workaround.

**Comment by mispy** [comment]
twitter_ebooks 3.1.1 now explicitly requires twitter ~> 5.15, thanks :)

**Comment by mispy** [comment]
wait, I misread that, sorry. hmmmm

**Comment by mispy** [comment]
twitter_ebooks 3.1.2 now explicitly requires twitter 5.14, until such time as there's a 5.16 >_>

**Comment by rachelhyman** [comment]
:+1:
